name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Añade estos permisos a nivel global
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build React app
        run: npm run build

  codeql:
    name: CodeQL (Frontend)
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      actions: read
      contents: read
      security-events: write # Esto es especialmente importante para CodeQL
    
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Analyze
        uses: github/codeql-action/analyze@v2